/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mlkfinalwork.TeaMenu;

import javax.swing.JOptionPane;

import mlkfinalwork.TeaIn.TeaImpl.TeaImpl;
import mlkfinalwork.TeaIn.TeaIn;
import mlkfinalwork.TeaUtils.UIUtil;
import mlkfinalwork.TeaFactory.TeacherUser;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
/**
 * @version 1.0 基于文本IO输入
 * @author 马苓珂
 */
public class TeaNewsModify extends javax.swing.JFrame {

    /**
     * Creates new form TeaNewsOutput
     */
    public TeaNewsModify(String tnum,String tname) {
        initComponents();
        init();
        showOldNews(tnum,tname);
    }

    private void showOldNews(String tnum , String tname) {
        BufferedReader br=null;
        try{
            br=new BufferedReader(new FileReader ("TeaUser.txt"));
            String line=null;
            while((line=br.readLine())!=null){
                String []datas=line.split("=");
                if(datas[0].equals(tnum)&&datas[1].equals(tname)){
                    this.jtftnumber.setText ( datas[0] );
                    this.jtftname.setText(datas[1]);
                    this.jtftaddr.setText(datas[2]);
                    this.jtftplace.setText(datas[3]);
                    this.jtftsex.setSelectedItem ( datas[4] );
                    this.jtfttel.setText(datas[5]);
                    this.jtfdhf.setText(datas[6]);
                    jtffz.setText(datas[7]);
                    jtfgjj.setText(datas[8]);
                    jtfsdf.setText(datas[10]);
                    jtfsds.setText(datas[11]);
                    jtfshbt.setText(datas[13]);
                    jtfjbgz.setText(datas[14]);
                    jtfjt.setText(datas[15]);
                    this.jtfwsf.setText(datas[16]);
                    /*
                        tu.getTnumber()+"="+tu.getTname()+"="+tu.getTaddress()+"="+
                        tu.getTplace()+"="+tu.getTsex()+"="+tu.getTtel()+"="+tu.getDhf()
                        +"="+tu.getFz()+"="+tu.getGjj()+"="+tu.getHjkk()+tu.getSdf()+"="+
                        tu.getSds()+tu.getSfgz()+"="+tu.getShbt()+"="+tu.getTjbgz()+"="+
                        tu.getTjt()+"="+tu.getWsf()+"="+tu.getYfgz()
                     */
                }
                break;
            }
        }catch(IOException ioe){
            ioe.printStackTrace();
        }finally{
            try {
                br.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtftsex = new javax.swing.JComboBox();
        jtftnumber = new javax.swing.JTextField();
        jtftname = new javax.swing.JTextField();
        jtfttel = new javax.swing.JTextField();
        jtftaddr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtftplace = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfgjj = new javax.swing.JTextField();
        jLabels = new javax.swing.JLabel();
        jtfgz = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jtfjbgz = new javax.swing.JTextField();
        jtffz = new javax.swing.JTextField();
        jtfjt = new javax.swing.JTextField();
        jLabel234 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel12312 = new javax.swing.JLabel();
        jtfsdf = new javax.swing.JTextField();
        jLabel999 = new javax.swing.JLabel();
        jtfshbt = new javax.swing.JTextField();
        jtfsds = new javax.swing.JTextField();
        jtfwsf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfdhf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("教师工资信息修改");

        jLabel2.setText("教师号");

        jLabel3.setText("姓名");

        jLabel4.setText("性别");

        jLabel5.setText("联系电话");

        jLabel6.setText("联系地址");

        jtftsex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "男", "女" }));

        jtftnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtftnumberActionPerformed(evt);
            }
        });

        jLabel7.setText("单位名称");

        jtftplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtftplaceActionPerformed(evt);
            }
        });

        jButton2.setText("取消");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("重置");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("卫生费");

        jLabels.setText("水电费");

        jtfgz.setText("房租");

        jlabel.setText("基本工资");

        jtfjt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfjtActionPerformed(evt);
            }
        });

        jLabel234.setText("津贴");

        jButton5.setText("完成");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12312.setText("生活补贴");

        jtfsdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfsdfActionPerformed(evt);
            }
        });

        jLabel999.setText("所得税");

        jLabel9.setText("电话费");

        jLabel10.setText("公积金");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel999, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtftsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabels))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtfsds, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtfdhf, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jtftplace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                            .addComponent(jtftaddr, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfttel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtftnumber, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtftname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(40, 40, 40))
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jlabel)
                                                            .addComponent(jLabel234))
                                                        .addComponent(jtfgz, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel12312))
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfjbgz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfjt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfsdf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfgjj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtffz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfshbt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfwsf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtftnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel)
                    .addComponent(jtfjbgz))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtftname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel234, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfjt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtftsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfsdf))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfgjj)
                    .addComponent(jLabel10))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtftaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfgz)
                    .addComponent(jtffz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtftplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12312, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfshbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel999)
                    .addComponent(jtfsds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtfwsf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfdhf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel999});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtftnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtftnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtftnumberActionPerformed

    private void jtftplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtftplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtftplaceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jtftaddr.setText("");
        this.jtftname.setText("");
        this.jtftnumber.setText("");
        this.jtftplace.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtfsdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfsdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfsdfActionPerformed

    private void jtfjtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfjtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfjtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        goLogin();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String teaNum=this.jtftnumber.getText();//教师号
        String teaNumRegex="\\d{10}";
        String teaName=this.jtftname.getText();//教师姓名
        String teaNameRegex="[^\\x00-\\xff]{2,4}";
        String teaAddr=this.jtftaddr.getText();
        String teaAddrRegex="[^\\x00-\\xff]{0,50}";
        String teaTel=this.jtfttel.getText();
        String teaTelRegex="[1]\\d{10}";
        String teaPlace=this.jtftplace.getText();
        String teaPlaceRegex="[^\\x00-\\xff]{0,50}";
        String teaSex=this.jtftsex.getName ();
        String fz=this.jtffz.getText();
        String numRegex="^\\d+(\\.\\d+)?$";
        String dhf=this.jtfdhf.getText();
        String gjj=this.jtfgjj.getText();
        String jbgz=this.jtfjbgz.getText();
        String jt=this.jtfjt.getText();
        String sds=this.jtfsds.getText();
        String sdf=this.jtfsdf.getText();
        String shbt=this.jtfshbt.getText();
        String wsf=this.jtfwsf.getText();
        if(!teaNum.matches(teaNumRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的教师号（10个数字组成）");
            this.jtftnumber.setText("");
            this.jtftnumber.requestFocus();
            return;
        }
        if(!teaName.matches(teaNameRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确格式的姓名（2-4个汉字）");
            this.jtftname.setText("");
            this.jtftname.requestFocus();
            return;
        }
        if(!teaAddr.matches(teaAddrRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的地址信息（不超过50个字符）");
            this.jtftaddr.setText("");
            this.jtftaddr.requestFocus();
            return;
        }
        if(!teaTel.matches(teaTelRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的电话号码(xxx-/xxxx-xxxxxxxx)");
            this.jtfttel.setText("");
            this.jtfttel.requestFocus();
            return;
        }
        if(!teaPlace.matches(teaPlaceRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的单位信息");
            this.jtftplace.setText("");
            this.jtftplace.requestFocus();
            return;
        }
        if(!fz.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jtffz.setText("");
            this.jtffz.requestFocus();
            return;
        }
        if(!gjj.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jtfgjj.setText("");
            this.jtfgjj.requestFocus();
            return;
        }
        if(!dhf.matches (numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jtfgjj.setText("");
            this.jtfgjj.requestFocus();
            return;
        }
        if(!jbgz.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jtfjbgz.setText("");
            this.jtfjbgz.requestFocus();
            return;
        }
        if(!jt.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jtfjt.setText("");
            this.jtfjt.requestFocus();
            return;
        }
        if(!sds.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jtfsds.setText("");
            this.jtfsds.requestFocus();
            return;
        }
        if(!gjj.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jtfshbt.setText("");
            this.jtfshbt.requestFocus();
            return;
        }
        if(!wsf.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jtfwsf.setText("");
            this.jtfwsf.requestFocus();
            return;
        }
        /*
        String gjj=this.gjj.getText();
        String jbgz=this.jbgz.getText();
        String jt=this.jt.getText();
        String sds=this.sds.getText();
        String sdf=this.sdf.getText();
        String shbt=this.shbt.getText();
        String wsf=this.jtfwsf.getText();
        */
        //封装成对象
        TeacherUser tu=new TeacherUser();
        tu.setTnumber(teaNum);
        tu.setTname(teaName);
        tu.setTaddress(teaAddr);
        tu.setTtel(teaTel);
        tu.setTplace(teaPlace);
        tu.setTsex(teaSex);
        tu.setFz(Double.parseDouble ( fz ));
        tu.setGjj(Double.parseDouble ( gjj ));
        tu.setTjbgz (Double.parseDouble ( jbgz ));
        tu.setDhf ( Double.parseDouble ( dhf ) );
        tu.setTjt (Double.parseDouble ( jt ));
        tu.setSds(Double.parseDouble ( sds));
        tu.setSdf(Double.parseDouble ( sdf ));
        tu.setShbt(Double.parseDouble ( shbt ));
        tu.setWsf(Double.parseDouble ( wsf ));
        //调用方法
        TeaIn ti=new TeaImpl ();
        boolean flag=false;
        flag=ti.modify(tu);
        //给出提示
        if(flag) {
            JOptionPane.showMessageDialog ( this , "修改成功！自动返回登录界面" );
            goLogin ();
        }else{
            JOptionPane.showMessageDialog ( this , "修改失败！检查一下再提交~" );
            return;
        }
    }//GEN-LAST:event_jButton5ActionPerformed
//返回登入界面
    private void goLogin() {
        WelCome w=new WelCome();
        this.dispose();
        w.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//         try {
//            /* Set the Nimbus look and feel */
//            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//            */
//            try {
//                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                    if ("Nimbus".equals(info.getName())) {
//                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                        break;
//                    }
//                }
//            } catch (ClassNotFoundException ex) {
//                java.util.logging.Logger.getLogger(WelCome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (InstantiationException ex) {
//                java.util.logging.Logger.getLogger(WelCome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (IllegalAccessException ex) {
//                java.util.logging.Logger.getLogger(WelCome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//                java.util.logging.Logger.getLogger(WelCome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            }
//            //</editor-fold>
//            UIManager.setLookAndFeel(MyLookAndFeel.JTATTOO_HIFI);
//            /* Create and display the form */
//            java.awt.EventQueue.invokeLater(new Runnable() {
//                public void run() {
//                    new TeaNewsOutput().setVisible(true);
//                }
//            });
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(WelCome.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            Logger.getLogger(WelCome.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            Logger.getLogger(WelCome.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            Logger.getLogger(WelCome.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12312;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel234;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel999;
    private javax.swing.JLabel jLabels;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField jtfdhf;
    private javax.swing.JTextField jtffz;
    private javax.swing.JTextField jtfgjj;
    private javax.swing.JLabel jtfgz;
    private javax.swing.JTextField jtfjbgz;
    private javax.swing.JTextField jtfjt;
    private javax.swing.JTextField jtfsdf;
    private javax.swing.JTextField jtfsds;
    private javax.swing.JTextField jtfshbt;
    private javax.swing.JTextField jtftaddr;
    private javax.swing.JTextField jtftname;
    private javax.swing.JTextField jtftnumber;
    private javax.swing.JTextField jtftplace;
    private javax.swing.JComboBox jtftsex;
    private javax.swing.JTextField jtfttel;
    private javax.swing.JTextField jtfwsf;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setTitle("教师基本信息修改");
        this.setResizable(false);
        UIUtil.setFrameCenter(this);
        UIUtil.setFrameImage(this);
    }
}
