/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mlkfinalwork.TeaMenu;

import javax.swing.JOptionPane;

import mlkfinalwork.TeaIn.TeaImpl.TeaImpl;
import mlkfinalwork.TeaIn.TeaIn;
import mlkfinalwork.TeaUtils.UIUtil;
import mlkfinalwork.TeaFactory.TeacherUser;

import java.util.ArrayList;

/**
 * @version 1.0 基于文本IO输入
 * @author 马苓珂
 */
public class TeaNewsOutput extends javax.swing.JFrame {

    /**
     * Creates new form TeaNewsOutput
     */
    public TeaNewsOutput() {
        initComponents();
        init();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtftsex = new javax.swing.JComboBox();
        jtftnumber = new javax.swing.JTextField();
        jtftname = new javax.swing.JTextField();
        jtfttel = new javax.swing.JTextField();
        jtftaddr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtftplace = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        gjj = new javax.swing.JTextField();
        jtfgjj = new javax.swing.JLabel();
        jtfsdf = new javax.swing.JLabel();
        jtfgz = new javax.swing.JLabel();
        jtfjbgz = new javax.swing.JLabel();
        jbgz = new javax.swing.JTextField();
        fz = new javax.swing.JTextField();
        jt = new javax.swing.JTextField();
        jtfjt = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jjj = new javax.swing.JLabel();
        sdf = new javax.swing.JTextField();
        jtfsds = new javax.swing.JLabel();
        shbt = new javax.swing.JTextField();
        sds = new javax.swing.JTextField();
        jtfwsf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfdhf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("教师信息填写");

        jLabel2.setText("教师号");

        jLabel3.setText("姓名");

        jLabel4.setText("性别");

        jLabel5.setText("联系电话");

        jLabel6.setText("联系地址");

        jtftsex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "男", "女" }));

        jtftnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtftnumberActionPerformed(evt);
            }
        });

        jLabel7.setText("单位名称");

        jtftplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtftplaceActionPerformed(evt);
            }
        });

        jButton2.setText("取消");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("重置");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("卫生费");

        jtfgjj.setText("公积金");

        jtfsdf.setText("水电费");

        jtfgz.setText("房租");

        jtfjbgz.setText("基本工资");

        jt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtActionPerformed(evt);
            }
        });

        jtfjt.setText("津贴");

        jButton5.setText("完成");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jjj.setText("生活补贴");

        sdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdfActionPerformed(evt);
            }
        });

        jtfsds.setText("所得税");

        jLabel9.setText("电话费");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfsds, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtftsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfsdf))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sds, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtfdhf, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jtftplace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                            .addComponent(jtftaddr, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfttel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtftnumber, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtftname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(40, 40, 40))
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jtfgjj))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jtfjbgz)
                                                            .addComponent(jtfjt))
                                                        .addComponent(jtfgz, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jjj))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbgz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gjj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shbt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfwsf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtftnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfjbgz)
                    .addComponent(jbgz))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtftname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfjt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtftsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfsdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sdf))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfgjj)
                    .addComponent(gjj))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtftaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfgz)
                    .addComponent(fz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtftplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfsds)
                    .addComponent(sds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtfwsf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfdhf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jtfsds});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtftnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtftnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtftnumberActionPerformed

    private void jtftplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtftplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtftplaceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jtftaddr.setText("");
        this.jtftname.setText("");
        this.jtftnumber.setText("");
        this.jtftplace.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdfActionPerformed

    private void jtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        goLogin();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String teaNum=this.jtftnumber.getText().trim ();//教师号
        String teaNumRegex="\\d{10}";
        String teaName=this.jtftname.getText().trim ();//教师姓名
        String teaNameRegex="[^\\x00-\\xff]{2,4}";
        String teaAddr=this.jtftaddr.getText();
        String teaAddrRegex="[^\\x00-\\xff]{0,50}";
        String teaTel=this.jtfttel.getText();
        String teaTelRegex="[1]\\d{10}";
        String teaPlace=this.jtftplace.getText();
        String teaPlaceRegex="[^\\x00-\\xff]{0,50}";
        String teaSex=this.jtftsex.getSelectedItem ().toString ();
        String fz=this.fz.getText();
        String numRegex="^\\d+(\\.\\d+)?$";
        String dhf=this.jtfdhf.getText();
        String gjj=this.gjj.getText();
        String jbgz=this.jbgz.getText();
        String jt=this.jt.getText();
        String sds=this.sds.getText();
        String sdf=this.sdf.getText();
        String shbt=this.shbt.getText();
        String wsf=this.jtfwsf.getText();
        if(!teaNum.matches(teaNumRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的教师号（10个数字组成）");
            this.jtftnumber.setText("");
            this.jtftnumber.requestFocus();
            return;
        }
        if(!teaName.matches(teaNameRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确格式的姓名（2-4个汉字）");
            this.jtftname.setText("");
            this.jtftname.requestFocus();
            return;
        }
        if(!teaAddr.matches(teaAddrRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的地址信息（不超过50个字符）");
            this.jtftaddr.setText("");
            this.jtftaddr.requestFocus();
            return;
        }
        if(!teaTel.matches(teaTelRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的电话号码(xxx-/xxxx-xxxxxxxx)");
            this.jtfttel.setText("");
            this.jtfttel.requestFocus();
            return;
        }
        if(!teaPlace.matches(teaPlaceRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的单位信息");
            this.jtftplace.setText("");
            this.jtftplace.requestFocus();
            return;
        }
        if(!fz.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.fz.setText("");
            this.fz.requestFocus();
            return;
        }
        if(!gjj.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.gjj.setText("");
            this.gjj.requestFocus();
            return;
        }
        if(!dhf.matches (numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.gjj.setText("");
            this.gjj.requestFocus();
            return;
        }
        if(!jbgz.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jbgz.setText("");
            this.jbgz.requestFocus();
            return;
        }
        if(!jt.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jt.setText("");
            this.jt.requestFocus();
            return;
        }
        if(!sds.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.sds.setText("");
            this.sds.requestFocus();
            return;
        }
        if(!gjj.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.shbt.setText("");
            this.shbt.requestFocus();
            return;
        }
        if(!wsf.matches(numRegex)){
            JOptionPane.showMessageDialog(this,"请输入正确的信息");
            this.jtfwsf.setText("");
            this.jtfwsf.requestFocus();
            return;
        }
        /*
        String gjj=this.gjj.getText();
        String jbgz=this.jbgz.getText();
        String jt=this.jt.getText();
        String sds=this.sds.getText();
        String sdf=this.sdf.getText();
        String shbt=this.shbt.getText();
        String wsf=this.jtfwsf.getText();
        */
        //封装成对象
        ArrayList<TeacherUser> al=new ArrayList <> (  );
        new TeaImpl().readTeacherUser ( al );
        boolean flag=false;
        for(int x=0;x<al.size();x++){
            //if(arr.get(x).getId()==id){
            if(al.get(x).getTnumber ().equals(teaNum)){
                flag=true;
            }
            if(flag){
                JOptionPane.showMessageDialog(this,"请输入正确的教师号（10个数字组成）");
                this.jtftnumber.setText ( "" );
                this.jtftnumber.requestFocus ();
                return;
            }
            else{
                break;
            }
        }
        TeacherUser tu=new TeacherUser();
        tu.setTnumber(teaNum);
        tu.setTname(teaName);
        tu.setTaddress(teaAddr);
        tu.setTtel(teaTel);
        tu.setTplace(teaPlace);
        tu.setTsex(teaSex);
        tu.setFz(Double.parseDouble ( fz ));
        tu.setGjj(Double.parseDouble ( gjj ));
        tu.setTjbgz (Double.parseDouble ( jbgz ));
        tu.setDhf ( Double.parseDouble ( dhf ) );
        tu.setTjt (Double.parseDouble ( jt ));
        tu.setSds(Double.parseDouble ( sds));
        tu.setSdf(Double.parseDouble ( sdf ));
        tu.setShbt(Double.parseDouble ( shbt ));
        tu.setWsf(Double.parseDouble ( wsf ));
        al.add(tu);
        //调用方法
        new TeaImpl ().regist ( al );
        //给出提示
        JOptionPane.showMessageDialog(this,"注册成功！自动返回登录界面");
        goLogin();
    }//GEN-LAST:event_jButton5ActionPerformed
//返回登入界面
    private void goLogin() {
        WelCome w=new WelCome();
        this.dispose();
        w.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//         try {
//            /* Set the Nimbus look and feel */
//            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//            */
//            try {
//                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                    if ("Nimbus".equals(info.getName())) {
//                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                        break;
//                    }
//                }
//            } catch (ClassNotFoundException ex) {
//                java.util.logging.Logger.getLogger(WelCome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (InstantiationException ex) {
//                java.util.logging.Logger.getLogger(WelCome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (IllegalAccessException ex) {
//                java.util.logging.Logger.getLogger(WelCome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//                java.util.logging.Logger.getLogger(WelCome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            }
//            //</editor-fold>
//            UIManager.setLookAndFeel(MyLookAndFeel.JTATTOO_HIFI);
//            /* Create and display the form */
//            java.awt.EventQueue.invokeLater(new Runnable() {
//                public void run() {
//                    new TeaNewsOutput().setVisible(true);
//                }
//            });
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(WelCome.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            Logger.getLogger(WelCome.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            Logger.getLogger(WelCome.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            Logger.getLogger(WelCome.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fz;
    private javax.swing.JTextField gjj;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jbgz;
    private javax.swing.JLabel jjj;
    private javax.swing.JTextField jt;
    private javax.swing.JTextField jtfdhf;
    private javax.swing.JLabel jtfgjj;
    private javax.swing.JLabel jtfgz;
    private javax.swing.JLabel jtfjbgz;
    private javax.swing.JLabel jtfjt;
    private javax.swing.JLabel jtfsdf;
    private javax.swing.JLabel jtfsds;
    private javax.swing.JTextField jtftaddr;
    private javax.swing.JTextField jtftname;
    private javax.swing.JTextField jtftnumber;
    private javax.swing.JTextField jtftplace;
    private javax.swing.JComboBox jtftsex;
    private javax.swing.JTextField jtfttel;
    private javax.swing.JTextField jtfwsf;
    private javax.swing.JTextField sdf;
    private javax.swing.JTextField sds;
    private javax.swing.JTextField shbt;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setTitle("教师基本信息填写");
        this.setResizable(false);
        UIUtil.setFrameCenter(this);
        UIUtil.setFrameImage(this);
    }
}
